[project]
name = "grpc-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.0",
    "grpcio-tools>=1.75.1",
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
]
