# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todoService/protos/todo_messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todoService/protos/todo_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&todoService/protos/todo_messages.proto\x12\x05todos\" \n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04task\x18\x02 \x01(\t\"\x1e\n\x0e\x41\x64\x64TodoRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\"+\n\x0f\x45\x64itTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04task\x18\x02 \x01(\t\"\x14\n\x06TodoId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\x11RemoveTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todoService.protos.todo_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODO']._serialized_start=49
  _globals['_TODO']._serialized_end=81
  _globals['_ADDTODOREQUEST']._serialized_start=83
  _globals['_ADDTODOREQUEST']._serialized_end=113
  _globals['_EDITTODOREQUEST']._serialized_start=115
  _globals['_EDITTODOREQUEST']._serialized_end=158
  _globals['_TODOID']._serialized_start=160
  _globals['_TODOID']._serialized_end=180
  _globals['_REMOVETODOREQUEST']._serialized_start=182
  _globals['_REMOVETODOREQUEST']._serialized_end=213
  _globals['_EMPTY']._serialized_start=215
  _globals['_EMPTY']._serialized_end=222
# @@protoc_insertion_point(module_scope)
