# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from todoService.protos import todo_messages_pb2 as todoService_dot_protos_dot_todo__messages__pb2
from todoService.protos import todo_service_pb2 as todoService_dot_protos_dot_todo__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in todoService/protos/todo_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TodoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTodo = channel.unary_unary(
                '/todos.TodoService/AddTodo',
                request_serializer=todoService_dot_protos_dot_todo__messages__pb2.AddTodoRequest.SerializeToString,
                response_deserializer=todoService_dot_protos_dot_todo__messages__pb2.Todo.FromString,
                _registered_method=True)
        self.EditTodo = channel.unary_unary(
                '/todos.TodoService/EditTodo',
                request_serializer=todoService_dot_protos_dot_todo__messages__pb2.EditTodoRequest.SerializeToString,
                response_deserializer=todoService_dot_protos_dot_todo__messages__pb2.Todo.FromString,
                _registered_method=True)
        self.GetTodo = channel.unary_unary(
                '/todos.TodoService/GetTodo',
                request_serializer=todoService_dot_protos_dot_todo__messages__pb2.TodoId.SerializeToString,
                response_deserializer=todoService_dot_protos_dot_todo__messages__pb2.Todo.FromString,
                _registered_method=True)
        self.ListTodos = channel.unary_unary(
                '/todos.TodoService/ListTodos',
                request_serializer=todoService_dot_protos_dot_todo__messages__pb2.Empty.SerializeToString,
                response_deserializer=todoService_dot_protos_dot_todo__service__pb2.ListTodosResponse.FromString,
                _registered_method=True)
        self.RemoveTodo = channel.unary_unary(
                '/todos.TodoService/RemoveTodo',
                request_serializer=todoService_dot_protos_dot_todo__messages__pb2.RemoveTodoRequest.SerializeToString,
                response_deserializer=todoService_dot_protos_dot_todo__service__pb2.RemoveTodoResponse.FromString,
                _registered_method=True)


class TodoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodo(self, request, context):
        """"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTodos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTodo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTodo,
                    request_deserializer=todoService_dot_protos_dot_todo__messages__pb2.AddTodoRequest.FromString,
                    response_serializer=todoService_dot_protos_dot_todo__messages__pb2.Todo.SerializeToString,
            ),
            'EditTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.EditTodo,
                    request_deserializer=todoService_dot_protos_dot_todo__messages__pb2.EditTodoRequest.FromString,
                    response_serializer=todoService_dot_protos_dot_todo__messages__pb2.Todo.SerializeToString,
            ),
            'GetTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodo,
                    request_deserializer=todoService_dot_protos_dot_todo__messages__pb2.TodoId.FromString,
                    response_serializer=todoService_dot_protos_dot_todo__messages__pb2.Todo.SerializeToString,
            ),
            'ListTodos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTodos,
                    request_deserializer=todoService_dot_protos_dot_todo__messages__pb2.Empty.FromString,
                    response_serializer=todoService_dot_protos_dot_todo__service__pb2.ListTodosResponse.SerializeToString,
            ),
            'RemoveTodo': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTodo,
                    request_deserializer=todoService_dot_protos_dot_todo__messages__pb2.RemoveTodoRequest.FromString,
                    response_serializer=todoService_dot_protos_dot_todo__service__pb2.RemoveTodoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'todos.TodoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('todos.TodoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TodoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.TodoService/AddTodo',
            todoService_dot_protos_dot_todo__messages__pb2.AddTodoRequest.SerializeToString,
            todoService_dot_protos_dot_todo__messages__pb2.Todo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.TodoService/EditTodo',
            todoService_dot_protos_dot_todo__messages__pb2.EditTodoRequest.SerializeToString,
            todoService_dot_protos_dot_todo__messages__pb2.Todo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.TodoService/GetTodo',
            todoService_dot_protos_dot_todo__messages__pb2.TodoId.SerializeToString,
            todoService_dot_protos_dot_todo__messages__pb2.Todo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTodos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.TodoService/ListTodos',
            todoService_dot_protos_dot_todo__messages__pb2.Empty.SerializeToString,
            todoService_dot_protos_dot_todo__service__pb2.ListTodosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTodo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/todos.TodoService/RemoveTodo',
            todoService_dot_protos_dot_todo__messages__pb2.RemoveTodoRequest.SerializeToString,
            todoService_dot_protos_dot_todo__service__pb2.RemoveTodoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
