# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todoService/protos/todo_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todoService/protos/todo_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from todoService.protos import todo_messages_pb2 as todoService_dot_protos_dot_todo__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%todoService/protos/todo_service.proto\x12\x05todos\x1a&todoService/protos/todo_messages.proto\"/\n\x11ListTodosResponse\x12\x1a\n\x05todos\x18\x01 \x03(\x0b\x32\x0b.todos.Todo\"%\n\x12RemoveTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8c\x02\n\x0bTodoService\x12-\n\x07\x41\x64\x64Todo\x12\x15.todos.AddTodoRequest\x1a\x0b.todos.Todo\x12/\n\x08\x45\x64itTodo\x12\x16.todos.EditTodoRequest\x1a\x0b.todos.Todo\x12%\n\x07GetTodo\x12\r.todos.TodoId\x1a\x0b.todos.Todo\x12\x33\n\tListTodos\x12\x0c.todos.Empty\x1a\x18.todos.ListTodosResponse\x12\x41\n\nRemoveTodo\x12\x18.todos.RemoveTodoRequest\x1a\x19.todos.RemoveTodoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todoService.protos.todo_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTTODOSRESPONSE']._serialized_start=88
  _globals['_LISTTODOSRESPONSE']._serialized_end=135
  _globals['_REMOVETODORESPONSE']._serialized_start=137
  _globals['_REMOVETODORESPONSE']._serialized_end=174
  _globals['_TODOSERVICE']._serialized_start=177
  _globals['_TODOSERVICE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
